# -*- coding: utf-8 -*-
"""telegrambots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m8sk-xzO5sZ3hnVpboI-qrKzEy1jsYhv

# Starting using telegram bots
getting messages
"""

import requests

resp = requests.get("https://api.telegram.org/bot5198206552:AAG6-73A47O0GnzNJcLWkG57OD8ICeV6eGU/getUpdates")
print(resp.text)

"""# Second part of getting messages
Reading data from group using parameters
"""

import requests

base_url="https://api.telegram.org/bot5198206552:AAG6-73A47O0GnzNJcLWkG57OD8ICeV6eGU/getUpdates"
parameters = {
    "offset": "367086623", #update id to start from
    "limit": "1" #number of messages to show
}
resp=requests.get(base_url, data=parameters)
print(resp.text)

"""# Sending Messages
Using the sendMessage endpoint
"""

import requests
import time

base_url="https://api.telegram.org/bot5198206552:AAG6-73A47O0GnzNJcLWkG57OD8ICeV6eGU/sendMessage"

jokes=['Did you hear about the mathematician who’s afraid of negative numbers? He’ll stop at nothing to avoid them.',
'Why do we tell actors to “break a leg?”Because every play has a cast. Here are some dark jokes to check out if you have a morbid sense of humor.',
'Helvetica and Times New Roman walk into a bar.“Get out of here!” shouts the bartender. “We don’t serve your type.”',
'Once my dog ate all the Scrabble tiles. For days he kept leaving little messages around the house. Don’t miss these hilarious egg puns that will absolutely crack you up.',
'Yesterday I saw a guy spill all his Scrabble letters on the road. I asked him, “What’s the word on the street?”',
'Once my dog ate all the Scrabble tiles. For days he kept leaving little messages around the house. Don’t miss these hilarious egg puns that will absolutely crack you up.'
]

for joke in jokes:
  parameters = {
      "chat_id": "-743974581", #specific chat id
      "text": joke #text message to send
  }
  resp=requests.get(base_url, data=parameters)
  print(resp.text)
  time.sleep(15)

"""# Sending Photos
sending images
"""

import requests
import time

base_url="https://api.telegram.org/bot5198206552:AAG6-73A47O0GnzNJcLWkG57OD8ICeV6eGU/sendPhoto"

images=['https://comparables.co.ke/static/blog/probability.png'
]

for image in images:
  parameters = {
      "chat_id": "-743974581", #specific chat id
      "photo": image, #image to send
      "caption": "Here is a test image from comparables website"
  }
  resp=requests.get(base_url, data=parameters)
  print(resp.text)
  time.sleep(15)

"""# Sending Audio files"""

import requests
import time

base_url="https://api.telegram.org/bot5198206552:AAG6-73A47O0GnzNJcLWkG57OD8ICeV6eGU/sendAudio"

audios=['https://www.bensound.com/bensound-music/bensound-ukulele.mp3',
        'https://www.bensound.com/bensound-music/bensound-anewbeginning.mp3',
        'https://www.bensound.com/bensound-music/bensound-littleidea.mp3'
]
#to send from a local computer just change the location to correspond to file navigation location, P.S. it may take some time to upgrade

for audio in audios:
  parameters = {
      "chat_id": "-743974581", #specific chat id
      "audio": audio, #image to send
      "caption": "Here is an audio file from bensound"
  }
  resp=requests.get(base_url, data=parameters)
  print(resp.text)
  time.sleep(15)

"""# sending any file from a local computer
<pdf, csv, doc, etc>
"""

import requests
import time

base_url="https://api.telegram.org/bot5198206552:AAG6-73A47O0GnzNJcLWkG57OD8ICeV6eGU/sendDocument"

documents=['/content/sample_data/mnist_test.csv',
           '/content/sample_data/mnist_train_small.csv'
]

for document in documents:
  parameters = {
      "chat_id": "-743974581", #specific chat id
      "caption": "Here is a file from drive/local"
  }
  files ={
      "document":document
  }
  resp=requests.get(base_url, data=parameters, files=files)
  print(resp.text)
  time.sleep(15)

"""# Creating Quizzes
Telegram Polls
"""

import requests
import time
import json

base_url="https://api.telegram.org/bot5198206552:AAG6-73A47O0GnzNJcLWkG57OD8ICeV6eGU/sendPoll"



#for image in images:
parameters = {
    "chat_id": "-743974581", #specific chat id
    "question": "Are you interested in bitcons or Ethereum?", #question to send
    "options": json.dumps(['Bitcons', 'Ethereum']),
    "is_anonymous": False
}
resp=requests.get(base_url, data=parameters)
print(resp.text)
time.sleep(15)

"""# Telegram Quiz"""

import requests
import time
import json

base_url="https://api.telegram.org/bot5198206552:AAG6-73A47O0GnzNJcLWkG57OD8ICeV6eGU/sendPoll"



#for image in images:
parameters = {
    "chat_id": "-743974581", #specific chat id
    "question": "How much is 100+200", #question to send
    "options": json.dumps(['1200', '300', '500', '2000']),
    "is_anonymous": False,
    "type":"quiz",
    "correct_option_id":1,
    "explanation": "learn some maths"
}
resp=requests.get(base_url, data=parameters)
print(resp.text)
time.sleep(15)