AWSTemplateFormatVersion: "2010-09-09"
Description: This to such terms.
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: Amazon EC2 instance type
    Type: String
    Default: m4.large
Resources:
  SharePointFoundationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and RDP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "3389"
          ToPort: "3389"
          CidrIp:
            Ref: SourceCidrForRDP
  SharePointFoundationEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId:
        Ref: SharePointFoundation
  SharePointFoundation:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
